substitutions:
  node_name: zigbee-rgbw-12-24v
  friendly_name: "Zigbee RGBW 12-24V"
  zigbee_channel: "15"
  zigbee_pan_id: "0x1AAA"
  zigbee_ext_pan_id: "00:11:22:33:44:55:66:77"
  zigbee_network_key: "[0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F]"

esphome:
  name: ${node_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c6-devkitc-1 # changer en esp32h2-devkitm-1 si H2
  framework:
    type: esp-idf

logger:

zigbee:
  channel: ${zigbee_channel}
  pan_id: ${zigbee_pan_id}
  extended_pan_id: ${zigbee_ext_pan_id}
  network_key: ${zigbee_network_key}

button:
  - platform: restart
    name: "${friendly_name} Reboot"

output:
  - platform: ledc
    pin: GPIO4
    id: r_out
  - platform: ledc
    pin: GPIO5
    id: g_out
  - platform: ledc
    pin: GPIO6
    id: b_out
  - platform: ledc
    pin: GPIO7
    id: w_out

light:
  - platform: rgbw
    name: "${friendly_name}"
    red: r_out
    green: g_out
    blue: b_out
    white: w_out
    default_transition_length: 300ms
    effects:
      - random:
      - strobe:
      - flicker:
